DIM intsleep AS INTEGER
DIM dbltime AS INTEGER
DIM userchoice AS STRING
DIM pass AS STRING
SCREEN 0
dbltime = 0
DO UNTIL dbltime = 5
CLS
PRINT "C:\>"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>_"
FOR intsleep = 0 TO 30000
NEXT intsleep
dbltime = dbltime + 1
LOOP
GOTO part2

part2:
dbltime = 0
CLS
PRINT "C:\>a"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
FOR intsleep = 0 TO 30000
NEXT intsleep
DO UNTIL dbltime = 8
CLS
PRINT "C:\>a:_"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
FOR intsleep = 0 TO 30000
NEXT intsleep
dbltime = dbltime + 1
LOOP
GOTO part3

part3:
dbltime = 0
DO UNTIL dbltime = 20
CLS
PRINT "C:\>a:"
PRINT "A:\>"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>_"
FOR intsleep = 0 TO 30000
NEXT intsleep
dbltime = dbltime + 1
LOOP
GOTO part4

part4:
dbltime = 0
CLS
PRINT "C:\>a:"
PRINT "A:\>q"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>qu_"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>qua"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quak_"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake_"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake "
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /_"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /l"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /lo_"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /loa"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /load_"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /load "
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /load -_"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /load -d"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /load -de_"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /load -dem"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /load -demo_"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /load -demo."
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /load -demo.d_"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /load -demo.dm"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /load -demo.dmo_"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /load -demo.dmo;"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /load -demo.dmo;d_"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /load -demo.dmo;de"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /load -demo.dmo;del_"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /load -demo.dmo;del "
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /load -demo.dmo;del d_"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /load -demo.dmo;del de"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /load -demo.dmo;del dem_"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /load -demo.dmo;del demo"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /load -demo.dmo;del demo._"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /load -demo.dmo;del demo.d"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /load -demo.dmo;del demo.dm_"
FOR intsleep = 0 TO 30000
NEXT intsleep
DO UNTIL dbltime = 15
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /load -demo.dmo;del demo.dmo"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /load -demo.dmo;del demo.dmo_"
FOR intsleep = 0 TO 30000
NEXT intsleep
dbltime = dbltime + 1
LOOP
GOTO finalpart

finalpart:
CLS
PRINT "C:\>a:"
PRINT "A:\>quake /load -demo.dmo;del demo.dmo_'"
INPUT "Please enter your Username:", pass
GOTO finalpart2

finalpart2:
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [          ]"
PRINT "                                     0%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [          ]"
PRINT "                                     1%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [          ]"
PRINT "                                     2%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [          ]"
PRINT "                                     3%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [          ]"
PRINT "                                     4%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [          ]"
PRINT "                                     5%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [          ]"
PRINT "                                     6%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [          ]"
PRINT "                                     7%"
FOR intsleep = 0 TO 30000
NEXT intsleep

CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [          ]"
PRINT "                                     8%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [          ]"
PRINT "                                     9%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [=         ]"
PRINT "                                    10%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [=         ]"
PRINT "                                    11%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [=         ]"
PRINT "                                    12%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [=         ]"
PRINT "                                    13%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [=         ]"
PRINT "                                    14%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [=         ]"
PRINT "                                    15%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [=         ]"
PRINT "                                    16%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [=         ]"
PRINT "                                    17%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [=         ]"
PRINT "                                    18%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [=         ]"
PRINT "                                    19%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [==        ]"
PRINT "                                    20%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [==        ]"
PRINT "                                    21%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [==        ]"
PRINT "                                    22%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [==        ]"
PRINT "                                    23%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [==        ]"
PRINT "                                    24%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [==        ]"
PRINT "                                    25%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [==        ]"
PRINT "                                    26%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [==        ]"
PRINT "                                    27%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [==        ]"
PRINT "                                    28%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [==        ]"
PRINT "                                    29%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [===       ]"
PRINT "                                    30%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [===       ]"
PRINT "                                    31%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [===       ]"
PRINT "                                    32%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [===       ]"
PRINT "                                    33%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [===       ]"
PRINT "                                    34%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [===       ]"
PRINT "                                    35%"
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [===       ]"
PRINT "                                    36% "
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [===       ]"
PRINT "                                    37% "
FOR intsleep = 0 TO 30000
NEXT intsleep
dbltime = 0
DO UNTIL dbltime = 10
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [=======   ]"
PRINT "                                    70% "
FOR intsleep = 0 TO 30000
NEXT intsleep
dbltime = dbltime + 1
LOOP
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loading"
PRINT "                               [========= ]"
PRINT "                                    96% "
FOR intsleep = 0 TO 30000
NEXT intsleep
CLS
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "                                  Loaded"
PRINT "                               [==========]"
PRINT "                                   100%"
FOR intsleep = 0 TO 30000
NEXT intsleep
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "Hello ", pass, ", Welcomt to Quake Demo"
PRINT "To Start, Follow the below instructions"
PRINT ""
PRINT "Press x to quit demo at any time"
PRINT ""
PRINT "Press c to continue"
DO
userchoice = INKEY$
IF userchoice = "x" OR userchoice = "X" THEN
GOTO Done
ELSEIF userchoice = "c" OR userchoice = "C" THEN
GOTO demo
END IF
LOOP WHILE (userchoice <> "x") AND (userchoice <> "X")

demo:
PRINT "File Error     "
dbltime = 0
DO UNTIL dbltime = 10
FOR intsleep = 0 TO 30000
NEXT intsleep
dbltime = dbltime + 1
LOOP
GOTO finalpart2

Done:
SCREEN 0
CLS





